name: Build and Push Image to Github Repository

on: workflow_call

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Tags
        id: generate-tags
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=false
          tags: |
            type=raw,value=dev,enable=${{github.ref_name != github.event.repository.default_branch}}
            type=raw,value=latest,enable=${{github.ref_name == github.event.repository.default_branch}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.generate-tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Summary
        run: |
          echo "### Build Success" >> $GITHUB_STEP_SUMMARY
          echo "Image pushed to\: \`${{steps.generate-tags.outputs.tags}}\`" >> $GITHUB_STEP_SUMMARY
