name: Lint

on: workflow_call

permissions:
  contents: read
  statuses: write

jobs:
  run-lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify code
        uses: super-linter/super-linter/slim@v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DOCKERFILE_HADOLINT: false
